### ISSUE TITLE
Help me install the software on a computer

### ISSUE THREAD

**Issue by ldhpm2** [GalAster/Mathpix#1]
I do not know how to install software on a computer to use, please help me.

**Comment by OrionSmedley** [comment]
It looks like the paclet is not found? 
![image](https://user-images.githubusercontent.com/61481323/109096775-0476be80-76d3-11eb-8428-2a987797433c.png)

**Comment by MinAndMid** [comment]
> I do not know how to install software on a computer to use, please help me.

Seems that you don't really know how to use Github. Just find the [release] area and download the lasted version of software.
